# Dockerfile.dev

# Use the official Bun image for linux/amd64
FROM --platform=linux/amd64 oven/bun:1.1.17

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy dependency management files to the container
COPY package.json bun.lockb ./

# Install dependencies with cache enabled
RUN bun install --frozen-lockfile

# Copy the rest of the application code to the container
COPY . .

# Copy the environment file for development and rename it to .env
# COPY .env.development ./.env

# Set the environment for development
ENV NODE_ENV=development

# Expose the port the app runs on
EXPOSE 3000

# Command to start the app in development mode
CMD ["bun", "run", "dev"]
